services:
  # Change Form data.
  Espin\PageInfoBundle\EventListener\PageInfo:
    public: true
    arguments:
      - "@request_stack"
    tags:
      - { name: contao.callback, table: tl_page, target: list.sorting.panel_callback.page_info, method: generatePanel }
      - { name: contao.callback, table: tl_article, target: list.sorting.panel_callback.article_info, method: generatePanel }
      - { name: contao.callback, table: tl_page, target: list.label.label, method: addPageHint }
      - { name: contao.callback, table: tl_article, target: list.label.label, method: addArticleHint }
